steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/markwave-backend'
      - 'backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'markwave-admin-dasboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/markwave-backend'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
    id: 'deploy-backend'
